import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

const baseUrl = import.meta.env.VITE_API_BASE_URL;

// Create API service
export const accountsApi = createApi({
  reducerPath: "accountsApi",
  baseQuery: fetchBaseQuery({ baseUrl }),
  endpoints: (builder) => ({
    registerAccount: builder.mutation({
      query: (account) => ({
        url: "/accounts/register", // your API endpoint
        method: "POST",
        body: account, // account = { firstName, lastName, email, password, organisation }
      }),
    }),
  }),
});

// Export hooks automatically generated by RTK Query
export const { useRegisterAccountMutation } = accountsApi;
