import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

const baseUrl = import.meta.env.VITE_API_BASE_URL;

// Create API service
export const accountsApi = createApi({
  reducerPath: "accountsApi",
  baseQuery: fetchBaseQuery({ baseUrl, credentials: "include" }),
  tagTypes: ["Account"],
  endpoints: (builder) => ({
    registerAccount: builder.mutation({
      query: (account) => ({
        url: "/accounts/register", // your API endpoint
        method: "POST",
        body: account, // account = { firstName, lastName, email, password, organisation }
      }),
    }),
    getAccountForUser: builder.query({
      query: () => `/accounts`,
      providesTags: ["Account"],
    }),
    updateAccount: builder.mutation({
      query: ({ data }) => ({
        url: `/accounts`,
        method: "PUT",
        body: data,
      }),
      invalidatesTags: ["Account"],
    }),
    deleteAccount: builder.mutation({
      query: () => ({
        url: `/accounts`,
        method: "DELETE",
      }),
    }),
  }),
});

// Export hooks automatically generated by RTK Query
export const {
  useRegisterAccountMutation,
  useGetAccountForUserQuery,
  useUpdateAccountMutation,
  useDeleteAccountMutation,
} = accountsApi;
